syntax = "proto2";

package TETRiS;

message RegionConfiguration {
  required string name = 1;
  required uint64 num_replicas = 2;
}

message RegionInfo {
  required string name = 1;
  message ReplicaInfo {
    message ProcessThread {
      required string process_name = 1;
      required uint64 thread_id = 2;
    }
    repeated ProcessThread process_thread = 1;
  }
  repeated ReplicaInfo replicas = 2;
}

message RegionThroughput {/* not yet defined */}

message RegularProcessInfo {
  required string name = 1;
  required uint64 thread_id = 2;
}

message NewClient {
  required uint32 pid = 1;
  required string exec = 2;
  required bool dynamic_client = 3;
  required string compare_criteria = 4;
  required bool compare_more_is_better = 5;
  optional string preferred_mapping = 7;
  optional string filter_criteria = 9;
}

message NewClientAck {
  required uint32 id = 1;
  required bool managed = 2;
}

message ClientRequest {
  enum Type {
    TETRIS_NEW_CLIENT = 0;
    DPM_SUBSCRIBE = 1;
    DPM_REGISTER_NEW_REGULAR_PROCESS = 2;
    DPM_REGISTER_NEW_PARALLEL_REGION = 3;
  }
  required Type type = 1;
  // TETRiS fields.
  optional NewClient new_client = 2;
  // DPM fields.
  optional RegularProcessInfo regular_process_info = 3;
  optional RegionInfo parallel_region_info = 4;
}

message ClientResponse {
  enum Type {
    ERROR = 0;
    ACKNOWLEDGE = 1;
    TETRIS_NEW_CLIENT_ACK = 2;
  }
  required Type type = 1;
  optional uint32 feature_id = 2;  /* After a subscription, the server returns the feature id allocated
                                      for the TETRiS feature. */
  // TETRiS fields.
  optional NewClientAck new_client_ack = 3;
}

message PushRequest {
  enum Type {
    UPDATE_CONFIGURATION = 0;
    GET_REGIONS_INFO = 1;
    GET_REGIONS_THROUGHPUT = 2;
  }
  required Type type = 1;
  required uint32 feature_id = 2;   /* Field used by the push server to forward the message
                                       to the corresponding TETRiS feature. */
  // DPM fields.
  repeated RegionConfiguration region_configurations = 3;
}

message PushResponse {
  enum Type {
    ERROR = 0;
    ACKNOWLEDGE = 1;
    REGION_INFO = 2;
    REGION_THROUGHPUT = 3;
  }
  required Type type = 1;
  // DPM fields.
  repeated RegionInfo region_infos = 3;
  repeated RegionThroughput region_throughputs = 4;
}