syntax = "proto2";

package tetris;

// Registration message from the TETRiS client to the server
message RegistrationRequest {
    required uint32 pid = 1;        // PID of the client
    required string exec = 2;       // The executable to identify the client
}

message RegistrationResponse {
    required uint32 id = 1;         // The internal client ID
}

// All the messages send from the client to the server
message ClientMessage {
    enum Type {                     // The message types
        MAPPINGS = 1;               // Register mappings for the client
        OPTIMIZATION_TARGET = 2;    // Change optimization target for the client
        FEATURE_SUBSCRIBE = 3;      // Register as an application feature with the server
        REGISTER_THREAD = 4;        // Register a new thread that should be handled by TETRiS
        DELETE_THREAD = 5;          // Remove a thread again from the handling of TETRiS
    }
    required Type type = 1;

    message MappingsInfo {          // Additional data for MAPPINGS message
        message MappingData {
            message Characteristic {
                required string name = 1;   // The name that describes the characteristic
                required float value = 2;   // The value of the characteristic
            }
            repeated Characteristic characteristics = 1;

            message ThreadInfo {
                required string name = 1;   // The thread for which information should be provided
                required string cpu = 2;    // The CPU to which the thread should be assigned
            }
            repeated ThreadInfo threads = 2;
        }
        repeated MappingData mappings = 1;
    }
    optional MappingsInfo mappings_info = 2;

    message FeatureInfo {           // Additional data for the FEATURE_SUBSCRIBE message
        enum FeatureType {          // The type of the feature that we want to register
            MOVABLE_THREADS = 1;    // The application supports moving individual threads around
            SCALE_APPLICATION = 2;  // The application can dynamically scale its number of threads at runtime
        }
        required FeatureType type =1;
    }
    optional FeatureInfo feature_info = 3;

    message ThreadInfo {            // Additional data for the REGISTER_THREAD message
        required uint32 tid = 1;    // The ID of the thread

        optional string name = 2;   // The name of the thread if it is named
    }
    optional ThreadInfo thread_info = 4;
}

// Responses from the server to the client upon client messages
message ServerResponse {
    enum Type {                     // The message types
        ERROR = 1;                  // Generic error when processing the message
        ACKNOWLEDGE = 2;            // Generic acknowledge of messages
        FEATURE_ACKNOWLEDGE = 3;    // Acknowledge of a FEATURE_SUBSCRIBE message
    }
    required Type type = 1;

    message FeatureAckInfo {
        required uint32 id = 1;     // The ID of the registered feature so that later messages can be properly routed
    }
    optional FeatureAckInfo feature_ack_info = 2;
}

// All the messages send from the server to the client
message ServerMessage {
    required uint32 feature_id = 1; // The ID of the feature which should handle this message

    enum Type {                     // The message types
        MOVE_THREADS = 1;           // Request to move application threads to different CPUs
        SCALE_APPLICATION = 2;      // Request to scale the application to a different number of threads
    }
    required Type type = 2;

    message MoveThreadsInfo {       // Additional data for the MOVE_THREADS message
        message ThreadAssigment {
            required uint32 tid = 1;    // The ID of the thread that should be moved
            required uint32 cpu = 2;    // The CPU number, where the thread should be moved to
        }
        repeated ThreadAssigment thread_assignments = 1;
    }
    optional MoveThreadsInfo move_threads_info = 3;

    message ScaleApplicationInfo {  // Additional data for the SCALE_APPLICATION message
        required uint32 max_threads = 1;    // The number of threads the application should maximally scale to
    }
    optional ScaleApplicationInfo scale_application_info = 4;
}

// Responses from the client to the server upon server messages
message ClientResponse {
    enum Type {
        ERROR = 1;                  // Generic error when processing the message
        ACKNOWLEDGE = 2;            // Generic acknowledge of messages
    }
    required Type type = 1;
}
