syntax = "proto2";

package tetris;

// Registration message from the TETRiS client to the server
message RegistrationRequest {
    enum MappingType {
      COARSE_GRAINED = 1;           // Mapping is determined only by a set of CPUs
      FINE_GRAINED = 2;             // Mapping include thread-to-core pinning and/or application-specific knobs
    }
    required uint32 pid = 1;        // PID of the client
    required string exec = 2;       // The executable to identify the client
    required MappingType mapping_type = 3;
}

message RegistrationResponse {
    required uint32 id = 1;         // The internal client ID
}

// All the messages send from the client to the server
message ClientMessage {
    enum Type {                     // The message types
        OPERATING_POINTS = 1;       // Register all operation points for the client
        OPTIMIZATION_TARGET = 2;    // Change optimization target for the client
        FEATURE_SUBSCRIBE = 3;      // Register as an application feature with the server
    }
    required Type type = 1;

    message OperatingPointsInfo {   // Additional data for OPERATION_POINTS message
        message OPData {
            required string identifier = 1;

            repeated uint32 cpu_ids = 2;    // The platform specific IDs of the CPUs

            required double utility = 3;    // IPS
            required double power = 4;      // The power consumption
        }
        repeated OPData operating_points = 1;
    }
    optional OperatingPointsInfo ops_info = 2;

    message FeatureInfo {           // Additional data for the FEATURE_SUBSCRIBE message
        enum FeatureType {          // The type of the feature that we want to register
            MOVABLE_THREADS = 1;    // The application supports moving individual threads around
            SCALE_APPLICATION = 2;  // The application can dynamically scale its number of threads at runtime
            APPLICATION_PROGRESS = 3;   // The application will report its own progress to the TETRiS server
        }
        required FeatureType type =1;
    }
    optional FeatureInfo feature_info = 3;
}

// Responses from the server to the client upon client messages
message ServerResponse {
    enum Type {                     // The message types
        ERROR = 1;                  // Generic error when processing the message
        ACKNOWLEDGE = 2;            // Generic acknowledge of messages
        FEATURE_ACKNOWLEDGE = 3;    // Acknowledge of a FEATURE_SUBSCRIBE message
    }
    required Type type = 1;

    message FeatureAckInfo {
        required uint32 id = 1;     // The ID of the registered feature so that later messages can be properly routed
    }
    optional FeatureAckInfo feature_ack_info = 2;
}

// All the messages send from the server to the client
message ServerMessage {
    required uint32 feature_id = 1; // The ID of the feature which should handle this message

    enum Type {                       // The message types
        ACTIVATE_CUSTOM_OP = 1;       // Inform the client about the activated operation point (for fine-grained mapping types)
        ACTIVATE_CPUS = 2;            // Inform the client about the active CPUS (for coarse-grained mapping types)
    }
    required Type type = 2;

    message OperatingPointAllocation {    // The information of the activated operation point
        required string identifier = 1;         // The name of the operation point/mapping that should be activated

        message CPUConversion {                 // The conversion map that should be used when activating the mapping
            required uint32 cpu_id_from = 1;
            required uint32 cpu_id_to = 2;
        }
        repeated CPUConversion cpu_convs = 2;
    }
    optional OperatingPointAllocation activated_op_info = 3;

    message CPUAllocation {                  // The information of the activate operating point
        repeated uint32 cpu_ids = 1;         // The list of CPU affinities to activate
    }
    optional CPUAllocation activated_cpus = 4;
}

message MockServerMessage {
    enum Type {
        ACTIVATE_OP = 1;
        ACTIVATE_MAPPING = 2;
    }
    required Type type = 1;

    message MockOperatingPoint {
        repeated string cpus = 1;
    }
    optional MockOperatingPoint activated_op_info = 2;

    message MockMapping {
        message ThreadAllocation {
            required string name = 1;
            required string cpu = 2;
        }

        repeated ThreadAllocation thread_map = 1;
    }
    optional MockMapping activated_mapping_info = 3;
}

// Responses from the client to the server upon server messages
message ClientResponse {
    enum Type {
        ERROR = 1;                  // Generic error when processing the message
        ACKNOWLEDGE = 2;            // Generic acknowledge of messages
    }
    required Type type = 1;
}
